We need to use Java 8 as the runtime when creating the configurations, else some containers (such as JOnAS) have awkward failures such as java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException